DROP TABLE IF EXISTS dbo.Users;

CREATE TABLE [dbo].[Users]
(
    [Id] [INT] IDENTITY(1, 1) NOT NULL,
    [Username] [NVARCHAR](128) NOT NULL,
    [Email] [NVARCHAR](128) NOT NULL,
    [HashedPassword] [NVARCHAR](128) NOT NULL,
    [Role] [NVARCHAR](32) NOT NULL,
    [IsConfirmed] [BIT] NOT NULL,
    CONSTRAINT [PK_Users]
        PRIMARY KEY CLUSTERED ([Id] ASC)
        WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,
              ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
             ) ON [PRIMARY]
) ON [PRIMARY];
